### ISSUE TITLE
[FR] Some suggestion

### ISSUE THREAD

**Issue by Mara-Li** [grochowski/obsidian-folder-focus-mode#1]
1. Autofocus : It will be cool if we could autofocus on the last opened folder.
2. Disable on file-menu too
3. Enable on command palette.

Thank you for this plugin!

Also, could you check the release? It seems BRAT doesn't succeed to download it :(

**Comment by grochowski** [comment]
Thanks for suggestions! Check the 0.9.1 release - I've added the disable option for previously chosen folder, and there's a command that focuses on a parent directory of currently active file.

New release should work right, I hope - let me know if you still have an issue with brat

**Comment by Mara-Li** [comment]
Thanks for this quick update!
Do you think it can be possible to autofocus when click on a file/open a file? (using quick switcher)
To do that, you could add an option in settings 'active auto focus', and each time a file is opened, focus on the folder. 
Also, maybe add an option to 'choice' the hierarchy focused folder in auto-focus. For example: 
- First folder *from root*
- First folder *from file*

Ex with hierarchy : 
```
Obsidian root folder/
├─ 001 Folder example/
│  ├─ 001 A PROJECT/
│  │  ├─ Github project
├─ 002 Notes/
│  ├─ Snippet CSS
```

When opening `Github Project` : 
- With 'from root reading' will focus on `001 Folder Example`
- With 'from file reading' will focus on `001 A Project`



I love it so much btw! It is a functionality I want for a LOOOOOOONG time!

**Comment by grochowski** [comment]
@Mara-Li auto-focus added on 0.9.3 release, with an option to focus on the first folder from root. Thanks for the feedback, it turned out to be useful for me too!

**Comment by Mara-Li** [comment]
How it this work ? Because, when focus not enabled, clicking on any file don't focus on the folder.
