### ISSUE TITLE
Deeply nested folder structures - some way to simplify the view

### ISSUE THREAD

**Issue by TfTHacker** [grochowski/obsidian-folder-focus-mode#10]
This is a focused view of a folder, where I am only about 3 folders in. 
![CleanShot 2022-11-06 at 09 03 07](https://user-images.githubusercontent.com/69121180/200160507-cf5bcfd5-de20-4b35-916f-8ce3b59279cf.png)

I think for this plugin when in focus mode, there should be two useful things:
- Location: where am I, but in a simplified format. 
- Showing more of the actual file names

So in this example, instead of seeing each folder, one under the other, have just one root node with a summary like:

Areas > Teaching > 2022-11-07
and then files listed underneath

**Comment by grochowski** [comment]
@TfTHacker 
new version (0.9.9) introduces Simplified View (available as a setting in plugin settings; you can also map a key shortcut for it). 
It hides all of parent directories and provides a much cleaner view, especially when using nested folders. 

I didn't really work on showing the location, as it is visible in some themes (including the default one), right above the file contents and adding it to file tree in a clean way was tricky for me atm. 

Let me know if it works for you!

**Comment by TfTHacker** [comment]
This looks great! Subtle but effective change.

Thank you for implementing this.
