### ISSUE TITLE
v0.9.10 breaks task toggling in Live Preview

### ISSUE THREAD

**Issue by batrand** [grochowski/obsidian-folder-focus-mode#13]
With the latest version (0.9.10) installed, I can no longer click on a task (`- [ ] some task`) to toggle its complete state. 

Confirmed that the issue was not there in the previous version (0.9.9), and the issue goes away once I deactivate the plugin. The issue is not there if you're in Reading mode.

Steps:
- Have v0.9.10 installed, and be in Live Preview mode.
- Add a task anywhere (type `- [ ] some task`)
- Click on the checkbox. It does nothing.
- Disable the plugin, and click the checkbox again. It now toggles the task's complete state, as expected.
- Enable the plugin, go to Reading mode. The checkbox works.

Expected: checkbox toggling should work in Live Preview.

**Comment by grochowski** [comment]
thanks for the info - released 0.9.11 with a fix, let me know if it works :)

**Comment by batrand** [comment]
thanks for the quick fix @grochowski ! Can confirm that fixed the issue!
