### ISSUE TITLE
Please keep button on explorer after Obsidian restarted

### ISSUE THREAD

**Issue by ham1204** [grochowski/obsidian-folder-focus-mode#14]
I am comfortable using Obsidian thanks to your plugin.!!! Thanks for the simple amazing plugin!.

It is the eye icon that appears at the top of the navigation area, but it does not appear again until I turn the plugin on and off each time I restart the application.

Is it possible to have "Focus this File" added for files, for example, as it appears in the contextual menu when you right-click on a folder?

**Comment by grochowski** [comment]
@ham1204 update the plugin and let me know if it works for you. button should be visible after restarting and changing the setting won't need a reload too
