### ISSUE TITLE
[bug] Cannot return to focused folder from its subfolder

### ISSUE THREAD

**Issue by danieltomasz** [grochowski/obsidian-folder-focus-mode#15]
I like the  plugin <3
Currently I observed that when I click to view a subfolder in the focused folder, I cannot return to the folder the level above by simple browsing, I need to set again the focus on the level above.

**Comment by grochowski** [comment]
that's true, noticed it as well after the updates - working on a fix :)

**Comment by grochowski** [comment]
update the plugin - 0.9.12 should fix the issue :) let me know if it works!

**Comment by danieltomasz** [comment]
Yes, it works! Thank you!
