### ISSUE TITLE
[Bug] Focusing and Unfocusing a Folder Breaks Collapse

### ISSUE THREAD

**Issue by NobleKestrel** [grochowski/obsidian-folder-focus-mode#17]
# Expected Behavior
After focusing on a folder, when unfocusing the same folder and collapsing the folder by clicking on it in the folder tree, the folder should collapse without issue.

# Actual Behavior
After focusing on a folder, unfocusing on the same folder and collapsing it by clicking on the folder in the folder tree collapses the folder the first time, but uncollapsing and collapsing the folder again breaks it. The behavior persists until I focus and unfocus on another folder. 

The "Collapse All" functionality also does not collapse the previously focused folder.

Thank you for your time!

**Comment by bradhaas** [comment]
Having the same issue

**Comment by HaloGamer33** [comment]
Same here

**Comment by Hunanbean** [comment]
For what it's worth, same issue here

Thank you

**Comment by Marco-Zechner** [comment]
I have the same issue

**Comment by SYYDSN** [comment]
+1

**Comment by Michael679089** [comment]
> I have a similar bug. When I collapse a focused folder, I cannot un-collapse it.

Yeah man, like what the frick. I just misclicked and I can't un-collapse it anymore.

**Comment by Drakemoor** [comment]
You'll find attached the main.js of the plugin with a fixed bug. I'm not a programmer, but I found a way to make it work. 
Just replace the original file in the plugin folder and restart Obsidian. 
I hope this will help. 
[main.js.zip](https://github.com/grochowski/obsidian-folder-focus-mode/files/14186314/main.js.zip)

**Comment by Hunanbean-Collective** [comment]
I ran the code from @Drakemoor through a comparison. there is only a minor change, and it is not malicious. it Does solve this particular issue. Others issues are still present, but it does fix the 'unable to expand after collapse all'.

Thanks Drakemoor  and  grochowski

**Comment by Michael679089** [comment]
> You'll find attached the main.js of the plugin with a fixed bug. I'm not a programmer, but I found a way to make it work. Just replace the original file in the plugin folder and restart Obsidian. I hope this will help. [main.js.zip](https://github.com/grochowski/obsidian-folder-focus-mode/files/14186314/main.js.zip)

Okay thanks, but I used the script of another user from the pull request.

**Comment by 4n07h3r-0n3-3n61n33r** [comment]
❤️
