### ISSUE TITLE
Seems to have issue with long file list

### ISSUE THREAD

**Issue by ronrdev** [grochowski/obsidian-folder-focus-mode#2]
Some subfolders and files are not shown. I made a recording.

https://user-images.githubusercontent.com/13022919/166491996-f89f7116-ba2a-496c-a95e-98f25a640a9e.mp4

**Comment by grochowski** [comment]
@ronrdev is the issue still happening on the latest version (0.9.6)?

**Comment by ronrdev** [comment]
Yes, but it could be my config. I'm adding a video to show how to recreate the issue.

https://user-images.githubusercontent.com/13022919/186205335-c7036c2d-4970-494c-af56-0c5d6fee0412.mp4

**Comment by grochowski** [comment]
@ronrdev I managed to reproduce the error in my vault and provided a fix in the latest (0.9.7) version. Let me know if it works now

**Comment by ronrdev** [comment]
Sorry for the very late reply. 
The plugin is working as expected. I'm using the latest version of Obsidian after the big 1.0 release.

**Comment by grochowski** [comment]
Great to hear that! Thanks for the feedback:)

**Comment by Hunanbean** [comment]
This behavior seems to still be an issue when using the built in Expand/Collapse folders function. The vault has a lot of files and folders.

Version 0.9.11
To reproduce, Focus a folder and then click Obsidian's built in Expand/Collapse. The file tree contents disappear, at least for me. 
I have disabled other plugins looking for conflicts, but noted no change in the problem. It may require a Vault with a lot of files and folders.

To me, this is basically the most essential plugin. Thank you for creating and maintaining it!
