### ISSUE TITLE
[BUG] Mobile 

### ISSUE THREAD

**Issue by Mara-Li** [grochowski/obsidian-folder-focus-mode#3]
On IOS (at last my Ipad) : 
- The plugin prevent Obsidian to start (15000ms of starting)
- The plugin doesn't work at all.

Maybe the plugin crash at startup ? I don't know because I can't see the developper console :(

**Comment by grochowski** [comment]
@Mara-Li thanks for the feedback! let me know if the new release (0.9.2) resolves these issues. Right now it works just right on my iPhone, I'd need feedback from an iPad too :)

**Comment by Mara-Li** [comment]
hello.
Bad news, the plugin continue to slow down Obsidian at startup.
![image](https://user-images.githubusercontent.com/30244939/167685053-5f6c41c1-1b6f-45ad-a0ff-b3b2c58cfeaa.png)

**Comment by grochowski** [comment]
@Mara-Li I couldn't reproduce the error - I have checked with the new release (0.9.3) and it happens to load in 23ms on my iPad Pro (2017). Let me know if the issue still happens on your iPad after updating the plugin

**Comment by grochowski** [comment]
@Mara-Li is it still happening after the updates or can I close this issue :) ?

**Comment by Mara-Li** [comment]
I changed my way I enable plugin on mobile, so I don't know if the error persist... At last, I don't have any error for the moment !
