### ISSUE TITLE
Files and folders inside the focused folder disappear from the sidebar

### ISSUE THREAD

**Issue by alehandrof** [grochowski/obsidian-folder-focus-mode#4]
I have folder structure like this:
A > B > C, D

I focus on "B". The files within there, as well as the two folders "C" and "D", disappear from the sidebar so I can't navigate easily. I'm assuming this is a bug, rather than the intended behavior.

Edit: I figured out what the issue was. I was also using the "Automatically reveal active file" plugin. Is there any way that the two plugins could play along together?

**Comment by grochowski** [comment]
@alehandrof 
try out the newest release (0.9.3) - it introduces 'auto-focus' mode (enable it in settings) which should work with mentioned plugin (I've tested it with the plugin too and it works just fine). let me know if it solves your problem! :)

**Comment by alehandrof** [comment]
It did, but I stumbled across a possibly related bug: the focused folder disappeared altogether when I switched to Longform and then back to the File Explorer.

**Comment by ahmet-cetinkaya** [comment]
Same thing happening to me.

https://user-images.githubusercontent.com/53148314/179535194-aa2fb741-b6e5-487f-885f-3e2c2f264c53.mp4

**Comment by grochowski** [comment]
@alehandrof is the error still there on the latest version (0.9.6)?

**Comment by grochowski** [comment]
@ahmet-cetinkaya i managed to reproduce the error in my vault. fix provided in the new 0.9.7 version should work :) let me know if it does!

**Comment by thomascurro** [comment]
working brillantly thank you !!!
