### ISSUE TITLE
[bug] focus on folder doesnt work well with 0.15.x Obsidian

### ISSUE THREAD

**Issue by danieltomasz** [grochowski/obsidian-folder-focus-mode#7]
After the update the focus plugin show unexpected behaviour - after focusing on folder and unfolding the folder it doesnt show the files (the files are visible for a second and then the folder contain long empty scroll or the sidebar is empty)

**Comment by phillipjohnston** [comment]
It also happens when switching between files in a focused view

**Comment by alex-kovac** [comment]
I can confirm.

**Comment by Mara-Li** [comment]
Hello!
My Fork (you can check it in the PR) work with the last obsidian version. I also added somes cools options.

I don't think this plugin is maintained anymore, but I try to keep my fork up to date.

**Comment by danieltomasz** [comment]
@Mara-Li thanks!

**Comment by grochowski** [comment]
@Mara-Li thanks so much for the updates, couldn't keep up with anything recently - merging the changes and publishing the version so the obsidian community plugins repository gets the updated version too :)

**Comment by danieltomasz** [comment]
@Mara-Li thanks for your  work ;) 
@grochowski   in the readme of this  repository there this reference to the @Mara-Li  fork, is this intended? :) 
https://github.com/grochowski/obsidian-folder-focus-mode#:~:text=Using%20BRAT%20to,folder-focus-mode

**Comment by grochowski** [comment]
@danieltomasz not intended :) 

release available in obsidian community plugins. 
@Mara-Li thanks again :)
