### ISSUE TITLE
Console messages

### ISSUE THREAD

**Issue by TfTHacker** [grochowski/obsidian-folder-focus-mode#9]
This is a great plugin. Thank you for your efforts with it. Will you continue to update it?

I notice that its sending a lot of messages to the console. This is just fine, but it can be confusing for other developers with so many messages. I would suggest adding a debug switch into your settings to be able to toggle debugging on and off. 

Tnx!

**Comment by grochowski** [comment]
thanks! 
cleaned these messages in new version (0.9.9) :)
